# Generated by Django 5.2.1 on 2025-05-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fever', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('tiredness', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('dry_cough', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('difficulty_breathing', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('sore_throat', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('no_other_symptoms', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('body_pain', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('nasal_congestion', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('runny_nose', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('diarrhea', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=10)),
                ('oxygen_level', models.FloatField()),
            ],
        ),
    ]
