# Generated by Django 5.2.1 on 2025-05-18 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fever', models.BooleanField(default=False)),
                ('tiredness', models.BooleanField(default=False)),
                ('dry_cough', models.BooleanField(default=False)),
                ('difficulty_breathing', models.BooleanField(default=False)),
                ('sore_throat', models.BooleanField(default=False)),
                ('body_pain', models.BooleanField(default=False)),
                ('nasal_congestion', models.BooleanField(default=False)),
                ('runny_nose', models.BooleanField(default=False)),
                ('diarrhea', models.BooleanField(default=False)),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=1)),
                ('oxygen_level', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
