# Generated by Django 5.2.1 on 2025-05-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0002_alter_patient_body_pain_alter_patient_diarrhea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='no_other_symptoms',
        ),
    ]
